//
//  User+CoreDataClass.swift
//  Krona
//
//  Created by Aditya Gadiyar on 9/3/19.
//  Copyright © 2019 Krona Technologies Incorporated. All rights reserved.
//
//

// AUTO GENERATED BY XCODE FOR CORE DATA
import Foundation
import CoreData


public class User: NSManagedObject {

}
